// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250118164142_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Customer")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Nvarchar(256)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFileName = "1.jpg",
                            Name = "شیائومی مدل Redmi Note 13 Pro",
                            Price = 275000000.0,
                            Rate = 4
                        },
                        new
                        {
                            Id = 2,
                            ImageFileName = "2.jpg",
                            Name = "اپل مدل iPhone 13 CH 256",
                            Price = 575000000.0,
                            Rate = 3
                        },
                        new
                        {
                            Id = 3,
                            ImageFileName = "3.jpg",
                            Name = "اپل مدل iPhone 13 pro ZAA 128",
                            Price = 757000000.0,
                            Rate = 5
                        },
                        new
                        {
                            Id = 4,
                            ImageFileName = "4.jpg",
                            Name = "سامسونگ مدل Galaxy A15 128",
                            Price = 265000000.0,
                            Rate = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageFileName = "5.jpg",
                            Name = "سامسونگ مدل Galaxy A35 128",
                            Price = 219000000.0,
                            Rate = 3
                        },
                        new
                        {
                            Id = 6,
                            ImageFileName = "6.jpg",
                            Name = "سامسونگ مدل Galaxy A05 256",
                            Price = 175000000.0,
                            Rate = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageFileName = "7.jpg",
                            Name = "نوکیا مدل 1100",
                            Price = 75000000.0,
                            Rate = 5
                        },
                        new
                        {
                            Id = 8,
                            ImageFileName = "8.jpg",
                            Name = "سامسونگ مدل Galaxy A55 512",
                            Price = 143000000.0,
                            Rate = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageFileName = "9.jpg",
                            Name = "سامسونگ مدل Galaxy S24 512",
                            Price = 331000000.0,
                            Rate = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProdOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("ProdOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
